### ISSUE TITLE
A Colab notebook would be great

### ISSUE THREAD

**Issue by AdamGustavsson** [YuvalNirkin/fsgan#1]
Thanks for releasing the code!
A Colab notebook is a great way to help people get started. I'd really appreciate it as I find it much easier to get familiar with a new project like that.
Regards

**Comment by lzhbrian** [comment]
Same suggestion here! Thanks for releasing the code!
A trained weight for testing performance conveniently would also be nice.

**Comment by tdh4vn** [comment]
yep, A colab is a great way. Maybe Yuval busy, I'm waiting for install and run guide.

**Comment by YuvalNirkin** [comment]
Great suggestion! I will look into it I'll finish with all the sections.

**Comment by iamnoob1** [comment]
I would like to test, make a notebook please

**Comment by wangchao0899** [comment]
![image](https://user-images.githubusercontent.com/53893157/79953983-45001d00-84af-11ea-89b7-359522548f57.png)

**Comment by wangchao0899** [comment]
Under win10, an error will be reported when Computing face poses for video: "shinzo_abe_seq00.mp4", the path cannot be found.

python.exe D:/MyCode/fsgan/inference/swap.py ../docs/examples/shinzo_abe.mp4 -t ../docs/examples/conan_obrien.mp4 -o. --finetune --finetune_save --seg_remove_mouth
=> using GPU devices: 0

=> Loading face pose model: "hopenet_robust_alpha1.pth"...
=> Loading face landmarks model: "hr18_wflw_landmarks.pth"...
=> Loading face segmentation model: "celeba_unet_256_1_2_segmentation_v2.pth"...
=> Loading face reenactment model: "nfv_msrunet_256_1_2_reenactment_v2.1.pth"...
=> Loading face completion model: "ijbc_msrunet_256_1_2_inpainting_v2.pth"...
=> Loading face blending model: "ijbc_msrunet_256_1_2_blending_v2.pth"...
=> Computing face poses for video: "shinzo_abe_seq00.mp4"...
Traceback (most recent call last):
  File "D:/MyCode/fsgan/inference/swap.py", line 501, in <module>
    main(**vars(parser.parse_args()))
  File "D:/MyCode/fsgan/inference/swap.py", line 495, in main
    face_swapping(source[0], target[0], output, select_source, select_target)
  File "D:/MyCode/fsgan/inference/swap.py", line 239, in __call__
    source_cache_dir, source_seq_file_path, _ = self.cache(source_path)
  File "D:\MyCode\fsgan\preprocess\preprocess_video.py", line 463, in cache
    self.process_pose(input_path, output_dir, seq_file_path)
  File "D:\MyCode\fsgan\preprocess\preprocess_video.py", line 242, in process_pose
    in_vid = VideoInferenceDataset(curr_vid_path, transform=img_transforms)
  File "D:\MyCode\fsgan\fsgan\datasets\video_inference_dataset.py", line 29, in __init__
    self.width, self.height, self.total_frames, self.fps = get_video_info(vid_path)
  File "D:\MyCode\fsgan\fsgan\utils\video_utils.py", line 223, in get_video_info
    return get_media_info(vid_path)
  File "D:\MyCode\fsgan\fsgan\utils\video_utils.py", line 206, in get_media_info
    probe = ffmpeg.probe(media_path)
  File "C:\Users\Superwang\Anaconda3\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\Superwang\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Superwang\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2]


![image](https://user-images.githubusercontent.com/53893157/79955215-0c614300-84b1-11ea-80eb-37fb662618b0.png)

**Comment by YuvalNirkin** [comment]
@wangchao0899 
Are you running this from "fsgan/inference" directory?

**Comment by wangchao0899** [comment]
@YuvalNirkin 
work out，According Du Jun' s Job~
![image](https://user-images.githubusercontent.com/53893157/80009207-566f1680-84fb-11ea-9582-14d8549b6a09.png)
[fsganlab_update1.zip](https://github.com/YuvalNirkin/fsgan/files/4517628/fsganlab_update1.zip)

**Comment by iamnoob1** [comment]
invalid load key

**Comment by dobrosketchkun** [comment]
> 
> 
> @YuvalNirkin
> work out，According Du Jun' s Job~
> ![image](https://user-images.githubusercontent.com/53893157/80009207-566f1680-84fb-11ea-9582-14d8549b6a09.png)
> [fsganlab_update1.zip](https://github.com/YuvalNirkin/fsgan/files/4517628/fsganlab_update1.zip)

Hello! Something wrong with your Colab notebook, I get this error for all substeps in the Step 3:

`/content/drive/My Drive/fsganLab/fshome
=> using GPU devices: 0
=> Loading face pose model: "hopenet_robust_alpha1.pth"...
=> Loading face landmarks model: "hr18_wflw_landmarks.pth"...
=> Loading face segmentation model: "celeba_unet_256_1_2_segmentation_v2.pth"...
Traceback (most recent call last):
  File "swap.py", line 498, in <module>
    main(**vars(parser.parse_args()))
  File "swap.py", line 490, in main
    blending_model=blending_model, criterion_id=criterion_id, min_radius=min_radius, output_crop=output_crop)
  File "swap.py", line 119, in __init__
    cache_segmentation=True, smooth_segmentation=smooth_segmentation, seg_remove_mouth=seg_remove_mouth)
  File "/content/drive/My Drive/fsganLab/fshome/fsgan/preprocess/preprocess_video.py", line 191, in __init__
    self.S = load_model(seg_model, 'face segmentation', self.device) if cache_segmentation else None
  File "/content/drive/My Drive/fsganLab/fshome/fsgan/utils/utils.py", line 178, in load_model
    checkpoint = torch.load(model_path)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 763, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input`

**Comment by iamnoob1** [comment]
The fix
FSGAN（conda版v2）.zip
https://github.com/YuvalNirkin/fsgan/files/4519557/FSGAN.conda.v2.zip

**Comment by dobrosketchkun** [comment]
> 
> 
> The fix
> FSGAN（conda版v2）.zip
> https://github.com/YuvalNirkin/fsgan/files/4519557/FSGAN.conda.v2.zip

And again on swap.py step:
`/content/drive/My Drive/fsganLab/fshome
=> using GPU devices: 0
=> Loading face pose model: "hopenet_robust_alpha1.pth"...
=> Loading face landmarks model: "hr18_wflw_landmarks.pth"...
=> Loading face segmentation model: "celeba_unet_256_1_2_segmentation_v2.pth"...
Traceback (most recent call last):
  File "swap.py", line 498, in <module>
    main(**vars(parser.parse_args()))
  File "swap.py", line 490, in main
    blending_model=blending_model, criterion_id=criterion_id, min_radius=min_radius, output_crop=output_crop)
  File "swap.py", line 119, in __init__
    cache_segmentation=True, smooth_segmentation=smooth_segmentation, seg_remove_mouth=seg_remove_mouth)
  File "/content/drive/My Drive/fsganLab/fshome/fsgan/preprocess/preprocess_video.py", line 191, in __init__
    self.S = load_model(seg_model, 'face segmentation', self.device) if cache_segmentation else None
  File "/content/drive/My Drive/fsganLab/fshome/fsgan/utils/utils.py", line 178, in load_model
    checkpoint = torch.load(model_path)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 763, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.`

**Comment by ak9250** [comment]
@dobrosketchkun the weight files probably did not download correctly, go to the google drive folder and make a copy of the weights to your own folder that way you are not downloading the weights everytime

**Comment by YuvalNirkin** [comment]
Thank you for everyone involved.

The official Google Colab:
[https://colab.research.google.com/github/YuvalNirkin/fsgan/blob/master/inference/face_swapping.ipynb](https://colab.research.google.com/github/YuvalNirkin/fsgan/blob/master/inference/face_swapping.ipynb)
