### ISSUE TITLE
only use face segmentation part

### ISSUE THREAD

**Issue by ZYzhouya** [YuvalNirkin/fsgan#101]
Hi～thanks for your great work!

If I only want to use the face segmentation module, what preprocess (_transforms.Normalize and so on_) should be applied to input images? And how to convert the output of 'fsgan.models.simple_unet.UNet' to a standard mask?

Wait for your response, thx again!

**Comment by YuvalNirkin** [comment]
The preprocessing requires a detection step with a scale of 2.0 for the v1 models and 1.2 for the v2 models. All images are normalized using mean and std equal (0.5, 0.5, 0.5).
You can convert the segmentation prediction to a Boolean face mask using the following: ``seg == 1``.

**Comment by heyoon01** [comment]
Hi! I would also like to test out only the segmentation part.
Where do you mean by setting seg ==1 ?

Thanks
