### ISSUE TITLE
ModuleNotFoundError: no module named 'yacs'

### ISSUE THREAD

**Issue by eluzzi5** [YuvalNirkin/fsgan#105]
Already tried the following fixes:

(1) !%%bashMINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh
!MINICONDA_PREFIX=/usr/local
!wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
!chmod +x $MINICONDA_INSTALLER_SCRIPT
!./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

(2) !pip install yacs

(3) !pip install ninja yacs cython matplotlib tqdm opencv-python

(4) !conda install -c conda-forge/label/cf202003 yacs

Any suggestions? 
Thank you!

**Comment by DFGANDP** [comment]
In google colab specify version of python worked for me
Instead of:
!pip install yacs
Use
!python3.6 -m pip install yacs
By default yacs is installed in python 3.8 for some reason

**Comment by eluzzi5** [comment]
> In google colab specify version of python worked for me
> Instead of:
> !pip install yacs
> Use
> !python3.6 -m pip install yacs
> By default yacs is installed in python 3.8 for some reason

This worked for me! Thank you :)
