### ISSUE TITLE
hand occlusion face segmentation

### ISSUE THREAD

**Issue by charleswg** [YuvalNirkin/fsgan#114]
Is the face segmentation model in V1 and V2 able to handle hand occlusion?

Previous repos of face segmentation (face_swap) from you seems to handle hand occlusion, though I can't test them due to caffe requirement in Windows.

**Comment by charleswg** [comment]
Tested the face_swap caffe models via cv2.dnn. Hand over face occlusion seems not working very well and remains challenging.

To confirm, the face_swap caffe models use 0 mean normalization whereas the V1 and V2 model use 0.5 mean and 0.5 std for each channel.

Can you explain the meaning of scale used in V1 (2.0) vs V2 (1.2)?

**Comment by YuvalNirkin** [comment]
The face segmentation in this project does not support hand segmentation.
I don't really remember what normalization I used in the face segmentation project, I think only the larger 500x500 model was trained to support hand occlusions.

The scales (2.0 and 1.2) control the size of the bounding box used for cropping the image relative to the detected bounding box.
