### ISSUE TITLE
guides to training the model?

### ISSUE THREAD

**Issue by byeol5832** [YuvalNirkin/fsgan#118]
hi! I was trying to train the model by myself but it's hard to figure out what to do..
any plans on uploading the training guide? thank you!

**Comment by leonardodora** [comment]
i want that ,too~

**Comment by NROwind** [comment]
I also want that

**Comment by NROwind** [comment]
> hi! I was trying to train the model by myself but it's hard to figure out what to do..
> any plans on uploading the training guide? thank you!

Hello,do you know how to train now？

**Comment by ovyan** [comment]
Couldn't train the models provided for several hours due to a lot of bugs in the code. I'm not sure about the reproducibility of training the models. Maybe that's the reason the training steps were not provided in the description...

**Comment by YuvalNirkin** [comment]
Sorry I have been busy working on other papers. I'll add a guide in a few days.

**Comment by YuvalNirkin** [comment]
I added a training guide.
