### ISSUE TITLE
Reenact.py outputs file cropped

### ISSUE THREAD

**Issue by thelordlugo** [YuvalNirkin/fsgan#12]
Don’t know if it’s meant to happen, but when it outputs the video is cropped to the face

**Comment by YuvalNirkin** [comment]
Yes this is on purpose.

The FSGAN algorithm generates a new face, it does not warp the source face. 
While this approach has some advantages over warping, it does lose most of the background information. 

Given a frontal face you can use the face mask to overwrite the original face and use the original background, but this is not implemented here.

**Comment by Sentero-esp12** [comment]
If someone finds this helpful, I've noticed that v1 reenactment.py doesn't crop as much, but it also uses a different reenactment algorithm I suppose
