### ISSUE TITLE
Where is the code for reenactment recursively and face-view interpolation?

### ISSUE THREAD

**Issue by moveslikejaekyu** [YuvalNirkin/fsgan#121]
Hi!
Thanks for offering great codes and paper.

But i got some problems with interpreting your offered code.

Where is the code for "define the reenactment output recursively" , "face-view interpolation" and "Using Poisson blending Loss"?

I matched many things that you mentioned in paper and codes, but the 3 topics are hard to find in here.

Hope you to point the 3 topics' code!

**Comment by YuvalNirkin** [comment]
Hi,

1. Recursive reenactment: [train_reenactment_stepwise.py](https://github.com/YuvalNirkin/fsgan/blob/v1/train_reenactment_stepwise.py) [reenactment_stepwise.py](https://github.com/YuvalNirkin/fsgan/blob/v1/inference/reenactment_stepwise.py)
2. Face view interpolation: [swap.py](https://github.com/YuvalNirkin/fsgan/blob/master/inference/swap.py#L311) and [appearance_map.py](https://github.com/YuvalNirkin/fsgan/blob/master/datasets/appearance_map.py)
3. Poisson blending loss: [train_blending.py](https://github.com/YuvalNirkin/fsgan/blob/master/train_blending.py)
