### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by Nesggy** [YuvalNirkin/fsgan#125]
Hello, I have this problem, and I've searched for a solution without success.
Some people said to reduce batch size, I've done it and I still the same error.
Others suggest to run this: torch.cuda.empty_cache() but I don't know how to run this command.
I only have 600Mb free, how can I increase it?
This is my error every time I execute swap.py or reenact.py.
After this step => Computing face segmentation for video:
I get this error:
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 8.00 GiB total capacity; 4.41 GiB already allocated; 615.77 MiB free; 5.48 GiB reserved in total by PyTorch)

**Comment by tushar-31093** [comment]
Why close this?

**Comment by Nesggy** [comment]
because trying to reduce the batch size solved by problem

**Comment by tushar-31093** [comment]
Any clue on how to resolve this?
![error](https://user-images.githubusercontent.com/40886260/116447971-35f83b80-a876-11eb-8841-9ae978119a08.png)

**Comment by tushar-31093** [comment]
Windows 10, Conda, Pytorch with CUDA, Batch size 1, Test image to target video

**Comment by Nesggy** [comment]
I added `-db 1 -pb 1 -lb 1 -sb 1`  at the end of the command

**Comment by tushar-31093** [comment]
Well, The above code is followed by this error now.


![error2](https://user-images.githubusercontent.com/40886260/116456454-f0407080-a87f-11eb-9e0b-e36821962641.png)

**Comment by Nesggy** [comment]
I think that's because you only have 4gb VRAM.
I have 8gb VRAM, and it's recommended to have 11gb I think
