### ISSUE TITLE
Inference for swap.py error

### ISSUE THREAD

**Issue by tushar-31093** [YuvalNirkin/fsgan#127]
Can anyone suggest a solution to this?
Windows 10, Conda, Pytorch with CUDA, Batch size 1, Test image to target video

![error](https://user-images.githubusercontent.com/40886260/116448205-78217d00-a876-11eb-9ee9-9061a71174c0.png)

**Comment by tushar-31093** [comment]
After adding : python swap.py input.mp4 -t 3.mp4 -o res.mp4 --seg_remove_mouth --encoder_codec mp4v -db 1 -pb 1 -lb 1 -sb 1


This error is coming now.

![error2](https://user-images.githubusercontent.com/40886260/116456629-19610100-a880-11eb-8859-e97ca8f79e10.png)

**Comment by YuvalNirkin** [comment]
4GB GPU is not enough for running the method. At least 8GB should be enough.
