### ISSUE TITLE
About the vgg19 that trained on Vggface2

### ISSUE THREAD

**Issue by NNNNAI** [YuvalNirkin/fsgan#132]
Thanks for your work. As you mentioned in the paper, you trained a vgg-19 CNN for vggface2 dataset for face recognition. How can I get this pretrained model. Thanks : )

**Comment by YuvalNirkin** [comment]
https://github.com/YuvalNirkin/fsgan/releases/download/v1.0.1/vggface2_vgg19_256_2_0_id.pth
