### ISSUE TITLE
removing frames from output video that has non-swapped faces

### ISSUE THREAD

**Issue by ItamarKanter** [YuvalNirkin/fsgan#133]
When using the default value for the _target selection method_ flag (_longest_) the output (verbose=0, --output_crop=False) includes target frames that weren't swapped. However, when setting --output_crop=True the output includes only frames with swapped faces.
How can I output a video (when --output_crop=False) that contains only frames with swapped faces?

**Comment by YuvalNirkin** [comment]
This not supported at the moment.
The logic for this behavior is in [video_renderer.py](https://github.com/YuvalNirkin/fsgan/blob/master/utils/video_renderer.py), you can simply comment out the two loops in the initialization and the end of sequence part respectively.

**Comment by ItamarKanter** [comment]
Thanks,
Works.
To be more precise, one should comment out only the lines:
`
self._render(frame_bgr)
`
in the aforementioned loops.
