### ISSUE TITLE
How do I swap faces on pictures instead of videos

### ISSUE THREAD

**Issue by wym-dlone** [YuvalNirkin/fsgan#148]
The article introduces the image can be face, I would like to ask how to image face.

**Comment by lxzatwowone1** [comment]
Just change the code a little, the essence of the video is the picture

**Comment by YuvalNirkin** [comment]
Target images are not yet supported in v2.
For now you can use [face_swap_images2images.py](https://github.com/YuvalNirkin/fsgan/blob/v1/inference/face_swap_images2images.py) from v1.

**Comment by nonlin** [comment]
For clarity when stated to use script with V1, does that mean copy script into V2 env or switch to a V1 Env and use said script?
