### ISSUE TITLE
About  No module named 'fsgan'

### ISSUE THREAD

**Issue by wym-dlone** [YuvalNirkin/fsgan#149]
Thank you very much for sharing the source code, but I have some questions to ask you.
When I run face_swap_images2images.py, This is the problem  : import fsgan.data.landmark_transforms as landmark_transforms
ModuleNotFoundError: No module named 'fsgan'. But I have followed the windows installation Guide.

**Comment by YuvalNirkin** [comment]
This is issue should be fixed now.
Follow the new installation instructions.
