### ISSUE TITLE
ModuleNotFoundError: No module named 'face_detection_dsfd'

### ISSUE THREAD

**Issue by Blade6570** [YuvalNirkin/fsgan#15]
I am getting this error from here: 
`File "../../fsgan/preprocess/preprocess_video.py", line 20, in <module>
    from face_detection_dsfd.face_detector import FaceDetector
`
I am wondering whether I need to install this [package](https://github.com/TencentYoutuResearch/FaceDetection-DSFD)? Please suggest .

**Comment by ak9250** [comment]
@Blade6570 you need to clone https://github.com/YuvalNirkin/face_detection_dsfd
