### ISSUE TITLE
filter_context method missing in landmarks_utils

### ISSUE THREAD

**Issue by arbeckmann** [YuvalNirkin/fsgan#152]
I am trying to train on reenactment with ijbc_msrunet_reenactment_attr_no_seg.py on my own data, as described in the train V2 tutorial. However it get the error:
AttributeError: module 'fsgan.utils.landmarks_utils' has no attribute 'filter_context'

How to solve?

**Comment by ppjjhh0911** [comment]
how to solve?

**Comment by YuvalNirkin** [comment]
The issue if fixed.
