### ISSUE TITLE
AttributeError: module 'fsgan.utils.landmarks_utils' has no attribute 'filter_context'

### ISSUE THREAD

**Issue by ppjjhh0911** [YuvalNirkin/fsgan#157]
I am trying to train on reenactment with ijbc_msrunet_reenactment_attr_no_seg.py on my own data, as described in the train V2 tutorial. However it get the error:
AttributeError: module 'fsgan.utils.landmarks_utils' has no attribute 'filter_context'

How to solve?

**Comment by ppjjhh0911** [comment]
@YuvalNirkin

**Comment by YuvalNirkin** [comment]
I fixed the issue. Please git pull and try again.
