### ISSUE TITLE
Remove Argparse and add custom source

### ISSUE THREAD

**Issue by thelordlugo** [YuvalNirkin/fsgan#17]
Can’t find a way to add a path to my own source and target on swap.py anyone know a way?

**Comment by jjandnn** [comment]
@thelordlugo 你是指你想修改swap.py？还是说，你添加了自己的源路径报错？
Do you mean you want to modify swap.py? Or did you add your own source path and report an error?

**Comment by thelordlugo** [comment]
Add my own source path so I won’t need to type -t, -o every time, I guess we have to modify the swap.py to do that

**Comment by YuvalNirkin** [comment]
Try placing your video files in a source and target directories and run:
```Bash
python swap.py <source directory> -t <target directory> -o <output directory>
```

**Comment by thelordlugo** [comment]
> Try placing your video files in a source and target directories and run:
> 
> ```Bash
> 
> python swap.py <source directory> -t <target directory> -o <output directory>
> 
> ```
> 
> 

That actually could work, but is there a way I can specify a path in swap.py? Thanks for the reply

**Comment by YuvalNirkin** [comment]
What do you mean by that? The source and target arguments in swap.py take in paths.

**Comment by thelordlugo** [comment]
Like I want to source to be equal to a string that changes every time I run the script, I want to declare the string inside swap.py but idk what variable to change to “example/location/file.mp4”

**Comment by YuvalNirkin** [comment]
Either write a script that calls the FaceSwapping class directly like in the [colab](https://colab.research.google.com/github/YuvalNirkin/fsgan/blob/master/inference/face_swapping.ipynb) or use one of the many available batch options like file lists or directories.
The swap.py interface is fine as it is.
