### ISSUE TITLE
ffprobe Error

### ISSUE THREAD

**Issue by AWGiaGia** [YuvalNirkin/fsgan#174]
=> using GPU devices: 0
=> Loading face pose model: "hopenet_robust_alpha1.pth"...
=> Loading face landmarks model: "hr18_wflw_landmarks.pth"...
=> Loading face segmentation model: "celeba_unet_256_1_2_segmentation_v2.pth"...
anaconda3/envs/fsgan/lib/python3.9/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484806139/work/aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
=> Loading face reenactment model: "nfv_msrunet_256_1_2_reenactment_v2.1.pth"...
=> Loading face completion model: "ijbc_msrunet_256_1_2_inpainting_v2.pth"...
=> Loading face blending model: "ijbc_msrunet_256_1_2_blending_v2.pth"...
=> Computing face poses for video: "1_seq00.mp4"...
ffprobe: error while loading shared libraries: libopenh264.so.5: cannot open shared object file: No such file or directory

How could I fix this error?

**Comment by AWGiaGia** [comment]
I know. I need to manually install the libopenh264.so.5 first.

**Comment by KleinXin** [comment]
conda install -c conda-forge ffmpeg
