### ISSUE TITLE
How can I make it work for images as source and target

### ISSUE THREAD

**Issue by mzmfarid** [YuvalNirkin/fsgan#22]
I want to swap images in stead of videos can you please tell me how can I do that. I tried to input images but it gives error.

> RuntimeError: Cache file does not exist: /content/data/source/source_dsfd_seq.pkl

**Comment by YuvalNirkin** [comment]
Right now target images are not supported in the latest version. In the v1 branch you can find the face_swap_images2images.py script. Source images can be used.

**Comment by mzmfarid** [comment]
Thank You
