### ISSUE TITLE
Matching implementation with the FSGAN Paper

### ISSUE THREAD

**Issue by Blade6570** [YuvalNirkin/fsgan#23]
Hi, Thanks for the great work. Is there any documented way to run the models that are trained as per the FSGAN paper? Default options point to *_v2.pth and I am wondering is this the one as described in the paper?  

When I try to pass the *_v1.pth paths it shows: 

`  File "../../fsgan/utils/utils.py", line 179, in load_model
    assert arch is not None or 'arch' in checkpoint, 'Couldn\'t determine %s model architecture!' % name
AssertionError: Couldn't determine face reenactment model architecture!
`
Please help in this regard.

**Comment by YuvalNirkin** [comment]
I will be adding a guide for the paper models soon.
In the meanwhile, I'll be happy to hear what do you compare against and on which datasets.

**Comment by YuvalNirkin** [comment]
[https://github.com/YuvalNirkin/fsgan/wiki/Paper-Models-Inference](https://github.com/YuvalNirkin/fsgan/wiki/Paper-Models-Inference)
