### ISSUE TITLE
Google Collab Demo and/or Examples of Reenactment?

### ISSUE THREAD

**Issue by BarryMode** [YuvalNirkin/fsgan#24]
Hey, is there a plan for a Google Collab demo and/or examples/tutorials _for Face Reenactment_?

**Comment by YuvalNirkin** [comment]
Yes, I plan to add more information on face reenactment.

**Comment by BarryMode** [comment]
Awesome, thanks for taking time to answer. Yours repo is by far the best I've seen with this tech!

**Comment by Sentero-esp12** [comment]
Hey @BarryMode, have you been able to create or find Google Colab notebooks for _Face Reenactment_?

**Comment by BarryMode** [comment]
No, I was patiently waiting to see if someone would make one.

**Comment by Sentero-esp12** [comment]
P.S. I was able to run it on Colab: https://colab.research.google.com/drive/12PD0W-UyFcTvrqCjrUb3LHPLlobGxi06?usp=sharing
It's very messy and has some redundant code (this is my first time creating a notebook), also it requires some Ubuntu knowledge and takes up to two hours to install dependencies.
