### ISSUE TITLE
v1 only using 67% of one gpu

### ISSUE THREAD

**Issue by thelordlugo** [YuvalNirkin/fsgan#29]
hi again, when using the face reincarnation on v1 it only uses around 67% of one 1080ti, and i have 4 of those cards with 0 percent utilization. my question is how do i get it to use all those gpus, in turn having a shorter export time.

**Comment by YuvalNirkin** [comment]
v1 isn't really optimized and multi-GPU is supported only in v2.
If your purpose is just to process multiple videos then you can run them each on separate GPU with:
```Bash
export NVIDIA_VISIBLE_DEVICES=<gpu_id>
```

**Comment by thelordlugo** [comment]
genius
