### ISSUE TITLE
AssertionError: Failed to read frame

### ISSUE THREAD

**Issue by jblee4sphinx** [YuvalNirkin/fsgan#32]
Hello, I get this error at the end of processing swap.py. Is there a fix for this? Thank you!

Process FaceSwappingRenderer-1:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data/dev/projects/fsgan/utils/video_renderer.py", line 159, in run
    assert frame_bgr is not None, f'Failed to read frame {i} from input video: "{self._in_vid_path}"'
AssertionError: Failed to read frame 1253 from input video: "../docs/examples/<video>.mp4"

**Comment by YuvalNirkin** [comment]
It seems to me that "../docs/examples/.mp4" is not an actual path to a video.
What is the full command you used?

**Comment by jblee4sphinx** [comment]
I removed the video filename prior to pasting. Here's the full command being run. The path is relative, similarly to how you did the shinzo and conan examples. I copied my source and target videos into the same directory with examples.

(base) root@ip-10-0-10-227:/data/dev/projects/fsgan/inference# python swap.py ../docs/examples/source_video.mp4 -t ../docs/examples/target_video.mp4 -o . --finetune --finetune_save --seg_remove_mouth

**Comment by YuvalNirkin** [comment]
Try re-encoding both videos with a standard encoding:
```Bash
ffmpeg -i <input video> -r 25 <output video>
```

**Comment by jblee4sphinx** [comment]
I finished re-encoding but now retrying the swap.py gives me an Assertion Error with CUDA. 
  File "/data/dev/projects/face_detection_dsfd/face_detector.py", line 19, in __init__
    assert torch.cuda.is_available(), 'CUDA must be available!'
AssertionError: CUDA must be available!

Is there a fix for this?

**Comment by YuvalNirkin** [comment]
Did you install the CUDA toolkit and NVIDIA driver?

**Comment by jblee4sphinx** [comment]
Yes. I followed every command step-by-step from https://github.com/YuvalNirkin/fsgan/wiki/Ubuntu-Installation-Guide. I will just rebuild and start over. Thanks for the help.

**Comment by BarryMode** [comment]
I had the same issue and can confirm that re-encoding both videos fixed the problem for me.

**Comment by harrodjordan** [comment]
I'm having this issue and re-encoding is not fixing the problem. Is there another workaround?
