### ISSUE TITLE
VideoRenderer hangs at end of swapping 

### ISSUE THREAD

**Issue by wagonduke** [YuvalNirkin/fsgan#33]
Hey,

I've been trying to reproduce [this](https://github.com/YuvalNirkin/fsgan/wiki/Face-Swapping-Inference) tutorial, namely just this command:
`python swap.py ../docs/examples/shinzo_abe.mp4 -t ../docs/examples/conan obrien.mp4 -o . --seg_remove_mouth`

The swapping process seems to work fine but hangs at the end on [this line](https://github.com/YuvalNirkin/fsgan/blob/46aa5020d1d21ed75e08da24c0b1d1d295312842/inference/swap.py#L357).

I looked further and it seems that there is an issue somewhere in the rendering pipeline, looks like it dies [here](https://github.com/YuvalNirkin/fsgan/blob/46aa5020d1d21ed75e08da24c0b1d1d295312842/utils/img_utils.py#L71) in the `img_tensor.clone()` operation. It looks like the video renderer doesn't even complete the processing of a single batch of frames so the completed boolean flag is never put on the `_reply_queue`?

If I trace the problem further back then I find that any operation applied to the tensors received from the multiprocessing `_input_queue` (e.g. a simple `.sum()`) seem to immediately kill the process, although their shape and values look fine if I print those. If I try an operation on the tensors immediately _before_ they are put on the queue then it works fine.

I don't know much at all about `pytorch.multiprocessing` but I found [this](https://pytorch.org/docs/stable/multiprocessing.html#sharing-cuda-tensors) and [this](https://discuss.pytorch.org/t/using-torch-tensor-over-multiprocessing-queue-process-fails/2847) which suggest that the `.put()` process should stay open until at least until the `.get()` process has finished (and maybe until the tensors have been processed?).

I tried using `.wait()` and `.set()` with a `pytorch.multiprocessing.Event()` to keep the `.put()` process open but it didn't help (maybe I'm doing it wrong).

I am running ubuntu on a docker container.

Any thoughts?

**EDIT:** I removed multiprocessing from VideoRenderer and it seems to work fine now - maybe this ok as a temporary fix if rendering performance isn't such an issue?

**Comment by YuvalNirkin** [comment]
The multiprocessing is now optional for the renderer (disabled by default). Just git pull and it should be working.

**Comment by chaaridev** [comment]
@wagonduke 
Can you please share your dockerfile , I tried to setup the project using docker but I'm getting few errors.
