### ISSUE TITLE
ModuleNotFoundError: No module named 'fsgan'

### ISSUE THREAD

**Issue by BarryMode** [YuvalNirkin/fsgan#34]
I'm trying to get reenact working in Google Colab. I was installing requirements and eventually got stuck on this one. I have fsgan in `/content/projects/fsgan`. Any help is much appreciated.

The error clearly indicating that it's not finding fsgan.

```bash
Traceback (most recent call last):
  File "/content/projects/fsgan/inference/reenact.py", line 23, in <module>
    from fsgan.preprocess.preprocess_video import VideoProcessBase, base_parser
ModuleNotFoundError: No module named 'fsgan'
```
I'm using it like this: `python reenact.py <source image> -t <target video> -o <output directory>` which I'm guessing is related to why it's not working.

I'll keep referring to the existing Colab and see if I can't figure it out.

**Comment by jajube** [comment]
You should add `/content/projects` to PYTHONPATH

```python
import sys
sys.path += ['/content/projects']
```

**Comment by BarryMode** [comment]
I got it working, thanks.

**Comment by DFGANDP** [comment]
I have same problem on colab

`Traceback (most recent call last):
  File "face_swap_images2images.py", line 11, in <module>
    import fsgan.data.landmark_transforms as landmark_transforms
ModuleNotFoundError: No module named 'fsgan'`

`import sys
sys.path += ['/content/projects']` 

doesnt work for me
my sys.path

`['',
 '/env/python',
 '/usr/lib/python36.zip',
 '/usr/lib/python3.6',
 '/usr/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.6/dist-packages/IPython/extensions',
 '/root/.ipython',
 '/usr/local/lib/python3.7/site-packages',
 '/content/projects']`

**Comment by mfahadgul77** [comment]
i am using on local vs but i have the problem like ModuleNotFoundError: No module named 'fsgan'.
how to solve it in VS code.
