### ISSUE TITLE
Dose face detection dsfd need  GPU DRAM out 12GB?  i meet out of memory in face detection step.

### ISSUE THREAD

**Issue by Dian-Yi** [YuvalNirkin/fsgan#35]
My GPU is TITANV, 12GB.
i run the command "python swap.py ../docs/examples/shinzo_abe.mp4 -t ../docs/examples/conan_obrien.mp4 -o . --finetune --finetune_save --seg_remove_mouth"
the error info: 
File "/git/face_detection_dsfd/face_ssd_infer.py", line 47, in forward
    return torch.cat((x1_1, x2_1, x3_1), 1)
RuntimeError: CUDA out of memory. Tried to allocate 1.98 GiB (GPU 0; 11.78 GiB total capacity; 8.08 GiB already allocated; 1.22 GiB free; 1.30 GiB cached)

I find that it processes shizao_abe.mp4 successfully, because its  resolution is 1280 x720. But conan_obrien.mp4 is failed, because its resolution 1920x1080. 
Does the resolution influence the detection DRAM?

**Comment by YuvalNirkin** [comment]
See #9.
