### ISSUE TITLE
[Question]Where to put my source image and destination video?

### ISSUE THREAD

**Issue by qendros123** [YuvalNirkin/fsgan#37]
Hello ,
Thank you for this code ,I was waiting so long for it.
I'm new at this one and I don't have any idea how to start the code .
Can you give me any explanation or tuto,where to put the source image and video destination ,where to do a training then ?
Can you give me a little help on it ?

Regards

**Comment by YuvalNirkin** [comment]
You can put them anywhere you want just follow the [inference guide](https://github.com/YuvalNirkin/fsgan/wiki/Face-Swapping-Inference).

I will add a training tutorial later on.
