### ISSUE TITLE
python download_fsgan_models.py   invalid syntax

### ISSUE THREAD

**Issue by qendros123** [YuvalNirkin/fsgan#38]
Hello ,
I have finish some steps but now I'm stuck at python download_fsgan_models.py 
I have filled the form and download the weight file but I don't have any idea where to put it and where to place download_fsgan_models.py. It says in the root directory of the fsgan repository but it doesn't work for me .
Can you explain me more in details these steps :
![Capture](https://user-images.githubusercontent.com/58636853/83342775-90e68300-a2f3-11ea-8294-ef3a5aa1a20b.JPG)

It show me like this : 

![Capture1](https://user-images.githubusercontent.com/58636853/83353305-f4070280-a351-11ea-85d4-a316bceab4c4.JPG)

**Comment by YuvalNirkin** [comment]
Did you try to run python from the python interpreter? Run it directly from the command prompt.
