### ISSUE TITLE
ModuleNotFoundError: No module named 'fsgan.utils'

### ISSUE THREAD

**Issue by qendros123** [YuvalNirkin/fsgan#39]
Can you help me on this error 
I don't have idea what I have done wrong.
Where to put fsgan and what to put on the projects folder.
There you can see my location of files

![1](https://user-images.githubusercontent.com/58636853/83958014-402fd680-a86d-11ea-9734-f1487ffca62f.jpg)

**Comment by YuvalNirkin** [comment]
You must use the repository in its original structure. The defaults paths will work only from the root directory of the repository.

**Comment by qendros123** [comment]
I run it in fsgan repository. I cloned fsgan and it directly goes to my documents file .
I put the download_fsgan_models there but it say modulenotfound .
