### ISSUE TITLE
Does v2 reenactment model have the version trained on ijbc datasets?

### ISSUE THREAD

**Issue by huangx06** [YuvalNirkin/fsgan#41]
Thanks for the great work!
Since v2 reenactment model downloaded is nfv_msrunet_256_1_2_reenactment_v2.1.pth, while v1 version is ijbc_msrunet_256_1_2_reenactment_stepwise_v1.
Did you train v2 on ijbc? could you release that model for downloading? Thanks!

**Comment by YuvalNirkin** [comment]
It was trained on IJBC with additional collected videos.
We might release an IJBC only models in the near future.
