### ISSUE TITLE
Can the train_reenactment_attr_no_seg_v2_1.py  be used for training? 

### ISSUE THREAD

**Issue by huangx06** [YuvalNirkin/fsgan#42]
I have debug this train_reenactment_attr_no_seg_v2_1.py file, but encounting many errors. Can this py file  be used for training, or would you release the training code?

**Comment by YuvalNirkin** [comment]
Yes, it goes together with a [configuration file](https://github.com/YuvalNirkin/fsgan/blob/master/experiments/reenactment/nfv_msrunet_reenactment_attr_no_seg_v2.1.py). The "root" variable should point to IJB-C's root directory.
I'll write a guide for training, the preprocessing of the dataset can be complicated.

**Comment by huangx06** [comment]
Thanks！ looking forward to your future works.
