### ISSUE TITLE
What to write on anaconda nav when I try to execute download_fsgan_models.py. ?

### ISSUE THREAD

**Issue by qendros123** [YuvalNirkin/fsgan#44]
Hello ,
I'm stuck in the step when I have to run the code download_fsgan_models.py ?
I have put this script in fsgan repository .But I don't know how should I run the code ?What should I write on anaconda navigator?
Please help me ,I'm stuck on this step already 3 weeks

**Comment by YuvalNirkin** [comment]
The exact commands are depicted in the [inference guide](https://github.com/YuvalNirkin/fsgan/wiki/Face-Swapping-Inference).

The commands should be written in the terminal (or command prompt in Windows) not in the anaconda navigator.

**Comment by qendros123** [comment]
For example my FSGAN repository is here  C:\Users\Qendrim\fsgan
How should I write in cmd to execute download_fsgan_models.py  ? Because when I'm doing it it show me this :  
I'm stuck here for 3-4 weeks and didn't find solution for that
![Capture](https://user-images.githubusercontent.com/58636853/85214665-5d38cf00-b36e-11ea-82ce-adc4764a3243.JPG)

**Comment by AIdeveloper-oz** [comment]
@qendros123 try changing `from fsgan.utils.utils import download_from_url`  to `from utils.utils import download_from_url`  and get rid of this issue.
