### ISSUE TITLE
Error during the call of swap inference script 

### ISSUE THREAD

**Issue by qendros123** [YuvalNirkin/fsgan#46]
When I try to call the swap inference script writing this command 

**python swap.py SOURCE -t TARGET -o OUTPUT [FLAGS]**

It show me this 
![Capture](https://user-images.githubusercontent.com/58636853/85237267-cdeef280-b425-11ea-8c87-69d5d195c7d5.JPG)

**Comment by YuvalNirkin** [comment]
You can't run python from within ipython.
