### ISSUE TITLE
Modulenotfound during the call of swap inference script

### ISSUE THREAD

**Issue by qendros123** [YuvalNirkin/fsgan#47]
I'm following the steps from Face Swapping Inference
I'm stuck on the second step trying to call the swap inference script 
When I run python swap.py it show me this error :
![Capture](https://user-images.githubusercontent.com/58636853/85346788-d8c58800-b4f6-11ea-9559-4530d86f4e05.JPG)

**Comment by Greg-Tarr** [comment]
This is due to incorrect file structure and/or not setting the PYTHONPATH variable as described in the [Windows Installation Guide](https://github.com/YuvalNirkin/fsgan/wiki/Windows-Installation-Guide)

**Comment by YuvalNirkin** [comment]
This issue should be resolved with the new installation fix.
