### ISSUE TITLE
Pytorch and torchvision version

### ISSUE THREAD

**Issue by shiyingZhang90** [YuvalNirkin/fsgan#5]
Hi Yuval.

I'm wondering what's your pytorch and torchvision version? There are several issues related to version mismatch I found, like "axis=1" => "dim=1" in hopenet.py, and self.inplace argument redundant in img_lms_pose_transform.py.

Thanks

**Comment by YuvalNirkin** [comment]
PyTorch 1.4.0 and Torchvision 0.5.0.

I'll update the code, thanks you.
