### ISSUE TITLE
The result on custom image is not good 

### ISSUE THREAD

**Issue by ayush-angelium** [YuvalNirkin/fsgan#52]
Hello @YuvalNirkin 
when I tested fsgan model on custom images using face_swap_images2images.py, the results look like this.
Sequence of image is : source img -> target img -> result img
Please let me know Is there any solution to resolve this issue.
![fsgan_img](https://user-images.githubusercontent.com/61581638/88625512-8283d000-d0c6-11ea-9b70-d5f3f9ec7dcf.png)

**Comment by AIdeveloper-oz** [comment]
Hi ayush, I tired the same process, but i get
 `Loading face segmentation model: "lfw_figaro_unet_256_2_0_segmentation_v1.pth"...
Loading face inpainting model: "ijbc_msrunet_256_2_0_inpainting_v1.pth"...
Traceback (most recent call last):
  File "face_swap_images2images.py", line 356, in <module>
    args.output_crop, args.display)
  File "face_swap_images2images.py", line 178, in main
    raise RuntimeError('No faces were detected in the source image directory: ' + source_path)
RuntimeError: No faces were detected in the source image directory: src_img/croppoints.jpg` [
![croppoints](https://user-images.githubusercontent.com/59594140/88653922-51b59200-d0ea-11ea-99cb-7eb2744aedf3.jpg)
![croppoints]

]I have also mentioned the image here. Help if you could.

**Comment by Hazeragged** [comment]
hello @AIdeveloper-oz  I have the same problem here,did you figure this out?

**Comment by wym-dlone** [comment]
Hi, I have the same problem here,did you figure this out?
