### ISSUE TITLE
ffmpeg._run.Error: ffprobe error (see stderr output for detail)

### ISSUE THREAD

**Issue by LiZhi1919** [YuvalNirkin/fsgan#53]
when i run **python swap.py ../docs/examples/shinzo_abe.mp4 -t ../docs/examples/conan_obrien.mp4 -o . --seg_remove_mouth**
under the directory fsgan/inference; i come out like the issue **"ffmpeg._run.Error: ffprobe error (see stderr output for detail)"**
Ubuntu 16.04 xshell

**Comment by TheshowN** [comment]
Hi, I met the same error. How did you fix it?
