### ISSUE TITLE
RuntimeError: No faces were detected in the source image directory

### ISSUE THREAD

**Issue by AIdeveloper-oz** [YuvalNirkin/fsgan#54]
I am using the v1 version. when I run the  **face_swap_images2images.py** , the image in the src dir is getting read and the pkl file is generated. But after that i get an error saying no face detected. Help me to come over! I have attached the image that i am testing.
![ChrisEvans](https://user-images.githubusercontent.com/59594140/89645873-5a6f4a80-d8d8-11ea-98b6-06d3a773c297.jpg)

**Comment by YuvalNirkin** [comment]
The face detector in v1 branch isn't that accurate but it might be that the face is too large, you can try resizing the image first.

**Comment by wjl520** [comment]
@AIdeveloper-oz    Hi, do you solve this problem about no face detected.

**Comment by AIdeveloper-oz** [comment]
Yeah, after resizing the images. as the author said.

> @AIdeveloper-oz Hi, do you solve this problem about no face detected.
