### ISSUE TITLE
No module named 'ffmpeg'

### ISSUE THREAD

**Issue by mhmddpkts** [YuvalNirkin/fsgan#57]
**No module named 'ffmpeg' error in installation part of official colab notebook.**

Notebook link: https://colab.research.google.com/github/YuvalNirkin/fsgan/blob/master/inference/face_swapping.ipynb

![ffmpeg error](https://user-images.githubusercontent.com/15729405/90369549-a65a8600-e074-11ea-9407-c7eb88d83b8f.png)

**Comment by tensorstrings** [comment]
You need to install the ffmpeg-python module to the environment:

`pip install ffmpeg-python`

from there `import ffmpeg` statements when using the environment should work.

**Comment by mhmddpkts** [comment]
> You need to install the ffmpeg-python module to the environment:
> 
> `pip install ffmpeg-python`
> 
> from there `import ffmpeg` statements when using the environment should work.

This solution already in notebook but it doesn't work. In addition, I tried this, but also it doesn't.

![Screenshot from 2020-08-19 07-53-27](https://user-images.githubusercontent.com/15729405/90593864-b8156800-e1f1-11ea-9cf4-add2f3606157.png)

**Comment by tensorstrings** [comment]
Try the fix from here: https://github.com/google/unrestricted-adversarial-examples/issues/42
It seems similar to your issue.

**Comment by mhmddpkts** [comment]
> Try the fix from here: [google/unrestricted-adversarial-examples#42](https://github.com/google/unrestricted-adversarial-examples/issues/42)
> It seems similar to your issue.


Thanks for your help @tensorstrings , Unfortunately, Restart to colab kernel does not work to me. But, Problem was solved, when I installed package with pip3.

`!pip3 install ffmpeg-python`
`import ffmpeg`

**Comment by dheerajmpai** [comment]
FFMPEG was installed in a different environment of python while the colab was running on another environment. 

Solution was to find out the path of ffmpeg using

```
!python
import ffmpeg
ffmpeg
```

Exit using `exit()`

Check you existing environment path

```
import cv2
cv2
```

Copy from one environment to other manually. In my case the following was the requirement

```
!cp -r /usr/local/lib/python3.8/site-packages/ffmpeg/ /usr/local/lib/python3.6/dist-packages/ffmpeg/
```

**Comment by limjinyung** [comment]
I did it like this

```
!git clone https://github.com/kkroening/ffmpeg-python.git
import sys
sys.path.append('/content/ffmpeg-python')
```

**Comment by benhassaini** [comment]
import subprocess
pathFFmpeg = r'C:\ProgramData\anaconda3\Library\bin\ffmpeg.exe'
pathInput = r'C:\ffmpeg\bin\bbb\in.mp4'
pathOutput = r'C:\ffmpeg\bin\bbb\out.mp4'
commands_list = [
    pathFFmpeg,
    "-i", pathInput,
    "-c:v", "libx265",
    "-preset", "fast",
    "-crf", "22",
    "-c:a", "aac",
    "-b:a", "196k",
    "-pix_fmt", "yuv420p", pathOutput
    ]    
results = subprocess.run(commands_list)
if results.returncode==0:
    print ("FFmpeg Script Ran Successfully")
else:
    print ("There was an error running your FFmpeg script")
