### ISSUE TITLE
Google colab ffmpeg

### ISSUE THREAD

**Issue by dobrosketchkun** [YuvalNirkin/fsgan#65]
It was working a few months ago, but now it's crashing with an error on the installation cell:

```
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-3-f17018d9ff88> in <module>()
     44 
     45 # Utility functions
---> 46 import ffmpeg
     47 
     48 def encode_audio(video_path, audio_path, output_path):

ModuleNotFoundError: No module named 'ffmpeg'

```

**Comment by Mohamed209** [comment]
may be coolab removed the package , so you may try to install it manually
`pip install ffmpeg-python`

**Comment by mhmddpkts** [comment]
@dobrosketchkun You can see this issue. This problem was solved. [Solution](https://github.com/YuvalNirkin/fsgan/issues/57)

**Comment by dobrosketchkun** [comment]
Thank you, it's working now.
