### ISSUE TITLE
RuntimeError: Tensors must have same number of dimensions: got 2 and 1

### ISSUE THREAD

**Issue by songyanbei** [YuvalNirkin/fsgan#66]
when i running  `python face_swap_images2images.py ../img/source_img/ -t ../img/target_img/ -o ./`  in V1

Traceback (most recent call last):
  File "face_swap_images2images.py", line 364, in <module>
    args.output_crop, args.display)
  File "face_swap_images2images.py", line 238, in main
    reenactment_input_tensor.append(torch.cat((curr_source_tensor[j], curr_target_landmarks[j]), dim=0).unsqueeze(0))
RuntimeError: Tensors must have same number of dimensions: got 2 and 1

What should I do?
thanks for your help!

**Comment by liudan193** [comment]
I also meet this issue, could you tell me how to solve it?
