### ISSUE TITLE
from fsgan.tests.test_soft_erosion_02 import SoftErosion

### ISSUE THREAD

**Issue by Bo396543018** [YuvalNirkin/fsgan#7]
where can i find tests directory？

**Comment by YuvalNirkin** [comment]
This might have been an issue that was already fixed as I don't see see this line in the code.
Can you try to git pull?

**Comment by Bo396543018** [comment]
> This might have been an issue that was already fixed as I don't see this line in the code.
> Can you try to git pull?

yes，i used a older version code  and pull new version can fix this. thank you
