### ISSUE TITLE
ffmpeg error 

### ISSUE THREAD

**Issue by sridhar9999** [YuvalNirkin/fsgan#71]
fatal: destination path 'face_detection_dsfd' already exists and is not an empty directory.
fatal: destination path 'fsgan' already exists and is not an empty directory.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-13-17308b460082> in <module>()
     25 
     26 # Utility functions
---> 27 import ffmpeg
     28 
     29 def encode_audio(video_path, audio_path, output_path):

ModuleNotFoundError: No module named 'ffmpeg'
 

i am getting this error in colab even after impporting manually install ffmpeg

**Comment by sajjadaemmi** [comment]
you can easily using conda and run this command:
`conda install -c conda-forge ffmpeg`

**Comment by sridhar9999** [comment]
It was on Colab something wrong I tried to install manually even after installed it gets the same error 

Is it good to install locally on only 4gb Nvidia card

**Comment by mhmddpkts** [comment]
This error solved in this [issue](https://github.com/YuvalNirkin/fsgan/issues/57).

**Comment by sridhar9999** [comment]
thanks for the help @mhmddpkts 

but why is it showing the error (no module named fsgan )

any remedy for that error i run local and even colab shows the same error

**Comment by lulin60** [comment]
> thanks for the help @mhmddpkts
> 
> but why is it showing the error (no module named fsgan )
> 
> any remedy for that error i run local and even colab shows the same error

you can try :
1:
echo 'export PYTHONPATH=$PYTHONPATH:/data/dev/projects' >> ~/.profile
source ~/.profile
2:
vim swap.py
add 'sys.path.append('../../') '  before line 'from fsgan.preprocess.preprocess_video import VideoProcessBase, base_parser'

**Comment by YuvalNirkin** [comment]
I have fixed this issue in the colab.
