### ISSUE TITLE
Video settings

### ISSUE THREAD

**Issue by theridefox** [YuvalNirkin/fsgan#8]
Good afternoon. Are there any restrictions on the length of the clips for processing, and a comparison of pre-trained models of versions 1 and 2 ,and how is it possible to improve video quality?

**Comment by YuvalNirkin** [comment]
There are no restrictions on the length of the clips.
I'll add a guide for the v1 models soon.
Video quality?

**Comment by theridefox** [comment]
> There are no restrictions on the length of the clips.
> I'll add a guide for the v1 models soon.
> Video quality?

Is it possible to output the file only in the form of a mask to increase its sharpness and make color-correction manually?

**Comment by YuvalNirkin** [comment]
It is possible but you will have to implement it yourself. You can take a look at the face swapping inference code when the verbose levels is set to 2.

![Example](https://raw.githubusercontent.com/wiki/YuvalNirkin/fsgan/media/swap_v2.gif)
