### ISSUE TITLE
Multiple faces in source or target video

### ISSUE THREAD

**Issue by BenjaminChua** [YuvalNirkin/fsgan#85]
My target video (or source for that matter) has 2 persons inside. I have checked that running swap.py would swap on only 1 person's face and in this case, it was the wrong person. May I ask what is the best way to filter out unwanted faces and only swap the chosen person's face?

**Comment by YuvalNirkin** [comment]
Use the --select_source and --select_target options with the ids the requested faces.
Take a look at the cache directory to see the detected faces.

**Comment by BenjaminChua** [comment]
Thank you, this solved my issue.
