### ISSUE TITLE
ffmpeg._run.Error: ffprobe error (see stderr output for detail)

### ISSUE THREAD

**Issue by wangjk666** [YuvalNirkin/fsgan#94]
Thanks a lot for your fantastic work. BTW, when I run the swap.py, it shows me an error 'ffmpeg._run.Error: ffprobe error (see stderr output for detail)', anybody knows how to fix this bug?

**Comment by damengdameng** [comment]
here is the resolution. #70

**Comment by wangjk666** [comment]
Ok, I have fixed this problem, thanks a lot.
